# Generated by Django 4.2.6 on 2023-10-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytracks', '0003_meep'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
