from django import forms
from django.forms import ModelForm
from .models import workout, ExcerciseList, training_routine, golf_course, golf_score

# Create a Workout Form
class WorkoutForm(ModelForm):
    class Meta:
        model = workout
        # fields = ('DetailID', 'WorkoutID', 'ExcerID', 'Region', 'Area', 'Exercise', 'SetOneReps', 'SetOneWeight', 'SetTwoReps', 'SetTwoWeight', 'SetThreeReps', 'SetThreeWeight', 'SetFourReps', 'SetFourWeight')
        fields = ('WorkoutName', 'Region', 'Area', 'Exercise', 'SetOneReps', 'SetOneWeight', 'SetTwoReps', 'SetTwoWeight', 'SetThreeReps', 'SetThreeWeight', 'SetFourReps', 'SetFourWeight')
        labels = {
            'WorkoutName': '',
            'Region': '',
            'Area': '',
            'Exercise': '',
            'SetOneReps': '',
            'SetOneWeight': '',
            'SetTwoReps': '',
            'SetTwoWeight': '',
            'SetThreeReps': '',
            'SetThreeWeight': '',
            'SetFourReps': '',
            'SetFourWeight': '',
        }
        widgets = {
            'WorkoutName': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Name'}),
            'Region': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Region'}),
            'Area': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Area'}),
            'Exercise': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Excercise'}),
            'SetOneReps': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'#1 Reps'}),
            'SetOneWeight': forms.TextInput(attrs={'class':'form-control', 'placeholder':'#1 Weight'}),
            'SetTwoReps': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'#2 Reps'}),
            'SetTwoWeight': forms.TextInput(attrs={'class':'form-control', 'placeholder':'#2 Weight'}),
            'SetThreeReps': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'#3 Reps'}),
            'SetThreeWeight': forms.TextInput(attrs={'class':'form-control', 'placeholder':'#3 Weight'}),
            'SetFourReps': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'#4 Reps'}),
            'SetFourWeight': forms.TextInput(attrs={'class':'form-control', 'placeholder':'#4 Weight'}),
        }

# Create an Excercise Form
class ExcerciseForm(ModelForm):
    class Meta:
        model = ExcerciseList
        fields = ('Reference', 'Region', 'Area', 'Exercise', 'Description', 'Instructions')
        labels = {
            'Reference': '',
            'Region': '',
            'Area': '',
            'Exercise': '',
            'Description': '',
            'Instructions': '',
        }
        widgets = {
            'Reference': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Reference'}),
            'Region': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Region'}),
            'Area': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Area'}),
            'Exercise': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Excercise'}),
            'Description': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Description', "rows": 3}),
            'Instructions': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Instructions', "rows": 3}),
        }

# Create an Routine Form
class RoutineForm(ModelForm):
    class Meta:
        model = training_routine
        fields = ('RoutineName', 'Description', 'Benefits', 'Instructions', 'ResultsComments')
        labels = {
            'RoutineName': '',
            'Description': '',
            'Benefits': '',
            'Instructions': '',
            'ResultsComments': '',
        }
        widgets = {
            'RoutineName': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Routnine'}),
            'Description': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Desciption'}),
            'Benefits': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Benefits'}),
            'Instructions': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Instructions', "rows": 3}),
            'ResultsComments': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Results & Comments'}),
        }

# Create an Golf Course Form
class GolfCourseForm(ModelForm):
    class Meta:
        model = golf_course
        fields = ('Course', 'CoursePar', 'Yards', 'Slope', 'Rating', 'Description',
                  'Hole1Par', 'Hole1Yardage', 'Hole1Handicap', 'Hole2Par', 'Hole2Yardage', 'Hole2Handicap',
                  'Hole3Par', 'Hole3Yardage', 'Hole3Handicap', 'Hole4Par', 'Hole4Yardage', 'Hole4Handicap',
                  'Hole5Par', 'Hole5Yardage', 'Hole5Handicap', 'Hole6Par', 'Hole6Yardage', 'Hole6Handicap',
                  'Hole7Par', 'Hole7Yardage', 'Hole7Handicap', 'Hole8Par', 'Hole8Yardage', 'Hole8Handicap',
                  'Hole9Par', 'Hole9Yardage', 'Hole9Handicap', 'Hole10Par', 'Hole10Yardage', 'Hole10Handicap',
                  'Hole11Par', 'Hole11Yardage', 'Hole11Handicap', 'Hole12Par', 'Hole12Yardage', 'Hole12Handicap',
                  'Hole13Par', 'Hole13Yardage', 'Hole13Handicap', 'Hole14Par', 'Hole14Yardage', 'Hole14Handicap',
                  'Hole15Par', 'Hole15Yardage', 'Hole15Handicap', 'Hole16Par', 'Hole16Yardage', 'Hole16Handicap',
                  'Hole17Par', 'Hole17Yardage', 'Hole17Handicap', 'Hole18Par', 'Hole18Yardage', 'Hole18Handicap',)
        labels = {
            'Course': '',
            'CoursePar': '',
            'Yards': '',
            'Slope': '',
            'Rating': '',
            'Description': '',
            'Hole1Par': '',
            'Hole1Yardage': '',
            'Hole1Handicap': '',
            'Hole2Par': '',
            'Hole2Yardage': '',
            'Hole2Handicap': '',
            'Hole3Par': '',
            'Hole3Yardage': '',
            'Hole3Handicap': '',
            'Hole4Par': '',
            'Hole4Yardage': '',
            'Hole4Handicap': '',
            'Hole5Par': '',
            'Hole5Yardage': '',
            'Hole5Handicap': '',
            'Hole6Par': '',
            'Hole6Yardage': '',
            'Hole6Handicap': '',
            'Hole7Par': '',
            'Hole7Yardage': '',
            'Hole7Handicap': '',
            'Hole8Par': '',
            'Hole8Yardage': '',
            'Hole8Handicap': '',
            'Hole9Par': '',
            'Hole9Yardage': '',
            'Hole9Handicap': '',
            'Hole10Par': '',
            'Hole10Yardage': '',
            'Hole10Handicap': '',
            'Hole11Par': '',
            'Hole11Yardage': '',
            'Hole11Handicap': '',
            'Hole12Par': '',
            'Hole12Yardage': '',
            'Hole12Handicap': '',
            'Hole13Par': '',
            'Hole13Yardage': '',
            'Hole13Handicap': '',
            'Hole14Par': '',
            'Hole14Yardage': '',
            'Hole14Handicap': '',
            'Hole15Par': '',
            'Hole15Yardage': '',
            'Hole15Handicap': '',
            'Hole16Par': '',
            'Hole16Yardage': '',
            'Hole16Handicap': '',
            'Hole17Par': '',
            'Hole17Yardage': '',
            'Hole17Handicap': '',
            'Hole18Par': '',
            'Hole18Yardage': '',
            'Hole18Handicap': '',
        }
        widgets = {
            'Course': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Course', 'size': '20'}),
            'CoursePar': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Par'}),
            'Yards': forms.TextInput(attrs={'class':'form-control', 'placeholder':'YDs'}),
            'Slope': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Slope'}),
            'Rating': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Rating'}),
            'Description': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Description','rows': 4, 'cols': 40}),
            'Hole1Par': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Par'}),
            'Hole1Yardage': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'YDs'}),
            'Hole1Handicap': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Hcp'}),
            'Hole2Par': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Par'}),
            'Hole2Yardage': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'YDs'}),
            'Hole2Handicap': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Hcp'}),
            'Hole3Par': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Par'}),
            'Hole3Yardage': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'YDs'}),
            'Hole3Handicap': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Hcp'}),
            'Hole4Par': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Par'}),
            'Hole4Yardage': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'YDs'}),
            'Hole4Handicap': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Hcp'}),
            'Hole5Par': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Par'}),
            'Hole5Yardage': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'YDs'}),
            'Hole5Handicap': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Hcp'}),
            'Hole6Par': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Par'}),
            'Hole6Yardage': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Yds'}),
            'Hole6Handicap': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Hcp'}),
            'Hole7Par': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Par'}),
            'Hole7Yardage': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'YDs'}),
            'Hole7Handicap': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Hcp'}),
            'Hole8Par': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Par'}),
            'Hole8Yardage': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'YDs'}),
            'Hole8Handicap': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Hcp'}),
            'Hole9Par': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Par'}),
            'Hole9Yardage': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'YDs'}),
            'Hole9Handicap': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Hcp'}),
            'Hole10Par': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Par'}),
            'Hole10Yardage': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'YDs'}),
            'Hole10Handicap': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Hcp'}),
            'Hole11Par': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Par'}),
            'Hole11Yardage': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'YDs'}),
            'Hole11Handicap': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Hcp'}),
            'Hole12Par': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Par'}),
            'Hole12Yardage': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'YDs'}),
            'Hole12Handicap': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Hcp'}),
            'Hole13Par': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Par'}),
            'Hole13Yardage': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'YDs'}),
            'Hole13Handicap': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Hcp'}),
            'Hole14Par': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Par'}),
            'Hole14Yardage': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'YDs'}),
            'Hole14Handicap': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Hcp'}),
            'Hole15Par': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Par'}),
            'Hole15Yardage': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'YDs'}),
            'Hole15Handicap': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Hcp'}),
            'Hole16Par': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Par'}),
            'Hole16Yardage': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'YDs'}),
            'Hole16Handicap': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Hcp'}),
            'Hole17Par': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Par'}),
            'Hole17Yardage': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'YDs'}),
            'Hole17Handicap': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Hcp'}),
            'Hole18Par': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Par'}),
            'Hole18Yardage': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'YDs'}),
            'Hole18Handicap': forms.TextInput(attrs={'class':'form-control placeholder', 'placeholder':'Hcp'}),
        }

class GolfScoreForm(ModelForm):
    class Meta:
        model = golf_score
        fields = ('GolfCourse', 'Score', 'Date', 'Player2', 'Player3', 'Player4',
                  'Hole1Par', 'Hole1Score', 'Hole2Par', 'Hole2Score', 'Hole3Par', 'Hole3Score',
                  'Hole4Par', 'Hole4Score', 'Hole5Par', 'Hole5Score', 'Hole6Par', 'Hole6Score',
                  'Hole7Par', 'Hole7Score', 'Hole8Par', 'Hole8Score', 'Hole9Par', 'Hole9Score',
                  'Hole10Par', 'Hole10Score', 'Hole11Par', 'Hole11Score', 'Hole12Par', 'Hole12Score',
                  'Hole13Par', 'Hole13Score', 'Hole14Par', 'Hole14Score', 'Hole15Par', 'Hole15Score',
                  'Hole16Par', 'Hole16Score', 'Hole17Par', 'Hole17Score', 'Hole18Par', 'Hole18Score', 'Comments')
        labels = {
            'GolfCourse': '',
            'Score': '',
            'Date': '',
            'Player2': '',
            'Player3': '',
            'Player4': '',
            'Hole1Par': '',
            'Hole1Score': '',
            'Hole2Par': '',
            'Hole2Score': '',
            'Hole3Par': '',
            'Hole3Score': '',
            'Hole4Par': '',
            'Hole4Score': '',
            'Hole5Par': '',
            'Hole5Score': '',
            'Hole6Par': '',
            'Hole6Score': '',
            'Hole7Par': '',
            'Hole7Score': '',
            'Hole8Par': '',
            'Hole8Score': '',
            'Hole9Par': '',
            'Hole9Score': '',
            'Hole10Par': '',
            'Hole10Score': '',
            'Hole11Par': '',
            'Hole11Score': '',
            'Hole12Par': '',
            'Hole12Score': '',
            'Hole13Par': '',
            'Hole13Score': '',
            'Hole14Par': '',
            'Hole14Score': '',
            'Hole15Par': '',
            'Hole15Score': '',
            'Hole16Par': '',
            'Hole16Score': '',
            'Hole17Par': '',
            'Hole17Score': '',
            'Hole18Par': '',
            'Hole18Score': '',
            'Comments': '',
        }
        widgets = {
            'GolfCourse': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Course', 'size': '20'}),
            'Score': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Score'}),
            'Date': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Date'}),
            'Player2': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Player'}),
            'Player3': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Player'}),
            'Player4': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Player'}),
            'Hole1Par': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Par'}),
            'Hole1Score': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Score'}),
            'Hole2Par': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Par'}),
            'Hole2Score': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Score'}),
            'Hole3Par': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Par'}),
            'Hole3Score': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Score'}),
            'Hole4Par': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Par'}),
            'Hole4Score': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Score'}),
            'Hole5Par': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Par'}),
            'Hole5Score': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Score'}),
            'Hole6Par': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Par'}),
            'Hole6Score': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Score'}),
            'Hole7Par': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Par'}),
            'Hole7Score': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Score'}),
            'Hole8Par': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Par'}),
            'Hole8Score': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Score'}),
            'Hole9Par': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Par'}),
            'Hole9Score': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Score'}),
            'Hole10Par': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Par'}),
            'Hole10Score': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Score'}),
            'Hole11Par': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Par'}),
            'Hole11Score': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Score'}),
            'Hole12Par': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Par'}),
            'Hole12Score': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Score'}),
            'Hole13Par': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Par'}),
            'Hole13Score': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Score'}),
            'Hole14Par': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Par'}),
            'Hole14Score': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Score'}),
            'Hole15Par': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Par'}),
            'Hole15Score': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Score'}),
            'Hole16Par': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Par'}),
            'Hole16Score': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Score'}),
            'Hole17Par': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Par'}),
            'Hole17Score': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Score'}),
            'Hole18Par': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Par'}),
            'Hole18Score': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Score'}),
            'Comments': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Round Summary'}),
        } 
    GolfCourse = forms.ModelChoiceField(queryset=golf_course.objects.all(), widget=forms.Select(attrs={'placeholder': 'Select a Golf Course'}), empty_label="Select a Golf Course")        