# Generated by Django 4.2.4 on 2023-10-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcerciseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExcerID', models.IntegerField(null=True)),
                ('Region', models.CharField(max_length=80, null=True)),
                ('Area', models.CharField(max_length=80, null=True)),
                ('Exercise', models.CharField(max_length=80, null=True)),
                ('Description', models.CharField(max_length=3000, null=True)),
                ('Instructions', models.CharField(max_length=3000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Excercises',
            },
        ),
        migrations.CreateModel(
            name='WorkoutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DetailID', models.IntegerField(null=True)),
                ('WorkoutID', models.IntegerField(null=True)),
                ('ExcerID', models.IntegerField(null=True)),
                ('Region', models.CharField(max_length=80, null=True)),
                ('Area', models.CharField(max_length=80, null=True)),
                ('Exercise', models.CharField(max_length=80, null=True)),
                ('SetOneReps', models.IntegerField(null=True)),
                ('SetOneWeight', models.CharField(max_length=80, null=True)),
                ('SetTwoReps', models.IntegerField(null=True)),
                ('SetTwoWeight', models.CharField(max_length=80, null=True)),
                ('SetThreeReps', models.IntegerField(null=True)),
                ('SetThreeWeight', models.CharField(max_length=80, null=True)),
                ('SetFourReps', models.IntegerField(null=True)),
                ('SetFourWeight', models.CharField(max_length=80, null=True)),
            ],
            options={
                'verbose_name_plural': 'Workout Excercise',
            },
        ),
        migrations.CreateModel(
            name='WorkoutHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkoutID', models.IntegerField(null=True)),
                ('WorkoutName', models.CharField(max_length=1000, null=True)),
                ('Frequency', models.CharField(max_length=220, null=True)),
                ('Level', models.CharField(max_length=80, null=True)),
                ('Description', models.CharField(max_length=3000, null=True)),
                ('Instructions', models.CharField(max_length=3000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Workout Name',
            },
        ),
    ]
