# Generated by Django 4.2.4 on 2023-10-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_excerciselist_workoutdetail_workoutheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutheader',
            name='WorkourType',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
