# Generated by Django 4.2.4 on 2023-10-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_remove_workoutheader_workourtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutdetail',
            name='WorkoutName',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
