# Generated by Django 4.2.4 on 2023-10-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_workoutdetail_workoutname'),
    ]

    operations = [
        migrations.CreateModel(
            name='workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkoutName', models.CharField(max_length=220, null=True)),
                ('ExcerID', models.IntegerField(null=True)),
                ('Region', models.CharField(max_length=80, null=True)),
                ('Area', models.CharField(max_length=80, null=True)),
                ('Exercise', models.CharField(max_length=80, null=True)),
                ('SetOneReps', models.IntegerField(null=True)),
                ('SetOneWeight', models.CharField(max_length=80, null=True)),
                ('SetTwoReps', models.IntegerField(null=True)),
                ('SetTwoWeight', models.CharField(max_length=80, null=True)),
                ('SetThreeReps', models.IntegerField(null=True)),
                ('SetThreeWeight', models.CharField(max_length=80, null=True)),
                ('SetFourReps', models.IntegerField(null=True)),
                ('SetFourWeight', models.CharField(max_length=80, null=True)),
            ],
            options={
                'verbose_name_plural': 'Workout Excercise',
            },
        ),
        migrations.DeleteModel(
            name='WorkoutDetail',
        ),
    ]
