# Generated by Django 4.2.4 on 2023-10-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_workout_delete_workoutdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='training_routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoutineName', models.CharField(max_length=120, null=True)),
                ('Description', models.CharField(max_length=1000, null=True)),
                ('Benefits', models.CharField(max_length=1000, null=True)),
                ('Instructions', models.CharField(max_length=1000, null=True)),
                ('ResultsComments', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Training Routine',
            },
        ),
    ]
