# Generated by Django 4.2.4 on 2023-10-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_training_routine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excerciselist',
            name='ExcerID',
        ),
        migrations.AddField(
            model_name='excerciselist',
            name='Reference',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
