# Generated by Django 4.2.4 on 2023-11-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0009_golf_course_golf_course_holwa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='golf_course_holwa',
            new_name='golf_course_holes',
        ),
    ]
