# Generated by Django 4.2.4 on 2023-11-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_rename_golf_course_holwa_golf_course_holes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='golf_course_holes',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Players',
        ),
        migrations.AddField(
            model_name='golf_course',
            name='CoursePar',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole10Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole10Handicap',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole10Par',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole10Score',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole10Yardage',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole11Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole11Handicap',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole11Par',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole11Score',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole12Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole12Handicap',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole12Par',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole12Score',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole12Yardage',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole13Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole13Handicap',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole13Par',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole13Score',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole13Yardage',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole14Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole14Handicap',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole14Par',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole14Score',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole14Yardage',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole15Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole15Handicap',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole15Par',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole15Score',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole15Yardage',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole16Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole16Handicap',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole16Par',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole16Score',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole16Yardage',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole17Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole17Handicap',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole17Par',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole17Score',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole17Yardage',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole18Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole18Handicap',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole18Par',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole18Score',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole18Yardage',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole1Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole1Handicap',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole1Par',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole1Score',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole1Yardage',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole2Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole2Handicap',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole2Par',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole2Score',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole2Yardage',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole3Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole3Handicap',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole3Par',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole3Score',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole3Yardage',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole4Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole4Handicap',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole4Par',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole4Score',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole4Yardage',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole5Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole5Handicap',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole5Par',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole5Score',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole5Yardage',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole6Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole6Handicap',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole6Par',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole6Score',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole6Yardage',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole7Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole7Handicap',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole7Par',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole7Score',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole7Yardage',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole8Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole8Handicap',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole8Par',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole8Score',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole9Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole9Handicap',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole9Par',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole9Score',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole9Yardage',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='golf_course',
            name='Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='golf_course',
            name='Rating',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='golf_course',
            name='Slope',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='golf_course',
            name='Yards',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
