# Generated by Django 4.2.4 on 2023-11-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_delete_golf_course_holes_remove_golf_course_players_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole10Score',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole11Score',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole12Score',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole13Score',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole14Score',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole15Score',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole16Score',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole17Score',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole18Score',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole1Score',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole2Score',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole3Score',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole4Score',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole5Score',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole6Score',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole7Score',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole8Score',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole9Score',
        ),
    ]
