# Generated by Django 4.2.4 on 2023-11-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0012_remove_golf_course_hole10score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole10Description',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole11Description',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole12Description',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole13Description',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole14Description',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole15Description',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole16Description',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole17Description',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole18Description',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole1Description',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole2Description',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole3Description',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole4Description',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole5Description',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole6Description',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole7Description',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole8Description',
        ),
        migrations.RemoveField(
            model_name='golf_course',
            name='Hole9Description',
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole11Yardage',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='golf_course',
            name='Hole8Yardage',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
