# Generated by Django 4.2.4 on 2023-10-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashInAcctM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountNumber', models.CharField(max_length=20, null=True)),
                ('Description', models.CharField(max_length=255, null=True)),
                ('DrCrBal', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashOutAcctM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountNumber', models.CharField(max_length=40, null=True)),
                ('Description', models.CharField(max_length=255, null=True)),
                ('DrCrBal', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Expense Accounts',
            },
        ),
        migrations.CreateModel(
            name='DebtsAcctM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountNumber', models.CharField(max_length=40, null=True)),
                ('Description', models.CharField(max_length=255, null=True)),
                ('DrCrBal', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Liability Accounts',
            },
        ),
        migrations.CreateModel(
            name='NetworthAcctM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountNumber', models.CharField(max_length=40, null=True)),
                ('Description', models.CharField(max_length=255, null=True)),
                ('DrCrBal', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Equity Accounts',
            },
        ),
        migrations.CreateModel(
            name='WhatWeOwnAcctM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountNumber', models.CharField(max_length=40, null=True)),
                ('Description', models.CharField(max_length=255, null=True)),
                ('DrCrBal', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Asset Accounts',
            },
        ),
    ]
