# Generated by Django 4.2.4 on 2023-11-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_personm'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementRollups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatementType', models.CharField(max_length=10, null=True)),
                ('Account', models.CharField(max_length=10, null=True)),
                ('RollupName', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Statement Rollups',
            },
        ),
    ]
