# Generated by Django 4.2.4 on 2023-11-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_statementrollups'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatementType', models.CharField(max_length=10, null=True)),
                ('Sequence', models.IntegerField(null=True)),
                ('LineName', models.CharField(max_length=12, null=True)),
            ],
            options={
                'verbose_name_plural': 'Statement Sections',
            },
        ),
    ]
