# Generated by Django 4.2.4 on 2023-11-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_statementsections_linename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementrollups',
            name='RollupName',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
