# Generated by Django 4.2.4 on 2023-11-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_cashinacctm_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashinacctm',
            name='DrCrBal',
        ),
    ]
