# Generated by Django 4.2.4 on 2023-11-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_remove_cashinacctm_drcrbal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashinacctm',
            options={'verbose_name_plural': 'Accounts'},
        ),
        migrations.AddField(
            model_name='cashinacctm',
            name='RollupType',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='cashinacctm',
            name='Section',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cashinacctm',
            name='Sequence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cashinacctm',
            name='Statement',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cashinacctm',
            name='Type',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
