# Generated by Django 4.2.4 on 2023-12-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_remove_statementsections_sequence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statementrollups',
            name='Account',
        ),
        migrations.AlterField(
            model_name='statementrollups',
            name='StatementType',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
