# Generated by Django 5.0 on 2024-01-06 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_remove_statementrollups_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementLinesHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LHName', models.CharField(max_length=240)),
                ('LHDescription', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='StatementLinesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SLNumber', models.IntegerField()),
                ('SLName', models.CharField(max_length=240)),
                ('StatementLinesDetailFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predecessor', to='transactions.statementlinesdetails')),
                ('StatementLinesHeaderFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.statementlinesheader')),
            ],
        ),
    ]
