# Generated by Django 5.0 on 2024-01-18 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_statementlinesheader_lhbalancesheet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementLineAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SAAccount', models.IntegerField()),
                ('SLAAccountType', models.CharField(max_length=12)),
                ('SLADescription', models.CharField(max_length=240)),
                ('SLAStatementAccountFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predecessor', to='transactions.statementlineaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='StatementLinesLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SLName', models.CharField(max_length=240)),
                ('SLDescription', models.CharField(max_length=240)),
                ('SLIncomeStatement', models.CharField(max_length=3, null=True)),
                ('SLIncomeStatementSection', models.CharField(max_length=80, null=True)),
                ('SLIncomeStatementSequence', models.IntegerField(null=True)),
                ('SLBalanceSheetStatement', models.CharField(max_length=3, null=True)),
                ('SLBalanceSheetStatementSection', models.CharField(max_length=80, null=True)),
                ('SLBalanceSheetStatementSequence', models.IntegerField(null=True)),
                ('SLCashFlowStatement', models.CharField(max_length=3, null=True)),
                ('SLCashFlowStatementSection', models.CharField(max_length=80, null=True)),
                ('SLCashFlowStatementSequence', models.IntegerField(null=True)),
                ('SLExpenseStatement', models.CharField(max_length=3, null=True)),
                ('SLExpenseStatementSection', models.CharField(max_length=80, null=True)),
                ('SLExpenseStatementSequence', models.IntegerField(null=True)),
                ('SLBudgetStatement', models.CharField(max_length=3, null=True)),
                ('SLBudgetStatementSection', models.CharField(max_length=80, null=True)),
                ('SLBudgetStatementSequence', models.IntegerField(null=True)),
                ('SLStatementLineFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predecessor', to='transactions.statementlinesline')),
            ],
        ),
        migrations.RemoveField(
            model_name='statementlinesdetails',
            name='StatementLinesDetailFK',
        ),
        migrations.RemoveField(
            model_name='statementlinesdetails',
            name='StatementLinesHeaderFK',
        ),
        migrations.DeleteModel(
            name='StatementRollups',
        ),
        migrations.AlterModelOptions(
            name='statementsections',
            options={},
        ),
        migrations.RemoveField(
            model_name='statementsections',
            name='LineName',
        ),
        migrations.RemoveField(
            model_name='statementsections',
            name='StatementType',
        ),
        migrations.AddField(
            model_name='statementlineaccounts',
            name='SLAStatementSectionFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.statementsections'),
        ),
        migrations.AddField(
            model_name='statementlinesline',
            name='SLStatementSectionFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.statementsections'),
        ),
        migrations.AddField(
            model_name='statementlineaccounts',
            name='SLAStatementLineFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.statementlinesline'),
        ),
        migrations.DeleteModel(
            name='StatementLinesDetails',
        ),
        migrations.DeleteModel(
            name='StatementLinesHeader',
        ),
    ]
