# Generated by Django 5.0 on 2024-01-20 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_statementlineaccounts_statementlinesline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementsections',
            name='SSBalanceSheetStatementSequence',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='statementsections',
            name='SSBalanceSheetStatementYN',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='statementsections',
            name='SSBudgetStatementSequence',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='statementsections',
            name='SSBudgetStatementYN',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='statementsections',
            name='SSCashFlowStatementSequence',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='statementsections',
            name='SSCashFlowStatementYN',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='statementsections',
            name='SSDescription',
            field=models.CharField(default='', max_length=960),
        ),
        migrations.AddField(
            model_name='statementsections',
            name='SSExpenseStatementSequence',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='statementsections',
            name='SSExpenseStatementYN',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='statementsections',
            name='SSIncomeStatementSequence',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='statementsections',
            name='SSIncomeStatementYN',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='statementsections',
            name='SSName',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='statementsections',
            name='SSPersonFK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.personm'),
        ),
    ]
