# Generated by Django 5.0 on 2024-01-21 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_statementsections_ssbalancesheetstatementsequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SName', models.CharField(default='', max_length=240)),
                ('SCurrentDate', models.DateTimeField(auto_now_add=True)),
                ('SFromDate', models.DateTimeField()),
                ('SThroughDate', models.DateTimeField()),
                ('SPostedDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TransBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransBatchName', models.CharField(max_length=120, null=True, unique=True)),
                ('TransBatchDate', models.DateField(null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('LastUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Transaction Batch',
            },
        ),
        migrations.CreateModel(
            name='TransDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('DrAccount', models.CharField(max_length=10, null=True)),
                ('CrAccount', models.CharField(max_length=10, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('LastUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Transaction Detail',
            },
        ),
        migrations.CreateModel(
            name='TransHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransDescription', models.CharField(max_length=120, null=True)),
                ('TransDate', models.DateField(null=True)),
                ('TransNote', models.CharField(max_length=240, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('LastUpdated', models.DateTimeField(auto_now=True)),
                ('TransBatchID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transbatch')),
            ],
            options={
                'verbose_name_plural': 'Transaction Header',
            },
        ),
        migrations.DeleteModel(
            name='CashOutAcctM',
        ),
        migrations.DeleteModel(
            name='DebtsAcctM',
        ),
        migrations.DeleteModel(
            name='NetworthAcctM',
        ),
        migrations.DeleteModel(
            name='WhatWeOwnAcctM',
        ),
        migrations.AddField(
            model_name='transdetail',
            name='TransHeaderID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transheader'),
        ),
    ]
