# Generated by Django 5.0 on 2024-01-22 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_statements_transbatch_transdetail_transheader_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statements',
            new_name='FinStatements',
        ),
    ]
