# Generated by Django 5.0 on 2024-01-22 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_rename_statements_finstatements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finstatements',
            old_name='SCurrentDate',
            new_name='FSCurrentDate',
        ),
        migrations.RenameField(
            model_name='finstatements',
            old_name='SFromDate',
            new_name='FSFromDate',
        ),
        migrations.RenameField(
            model_name='finstatements',
            old_name='SName',
            new_name='FSName',
        ),
        migrations.RenameField(
            model_name='finstatements',
            old_name='SPostedDate',
            new_name='FSPostedDate',
        ),
        migrations.RenameField(
            model_name='finstatements',
            old_name='SThroughDate',
            new_name='FSThroughDate',
        ),
    ]
