# Generated by Django 5.0 on 2024-04-01 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_remove_statementlinesline_slstatementlinefk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finstatements',
            name='FSCurrentDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='finstatements',
            name='FSFromDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='finstatements',
            name='FSPostedDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='finstatements',
            name='FSThroughDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sectionlines',
            name='SLStatementSectionsFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statementsectionlines_set', to='transactions.statementsections'),
        ),
    ]
