# Generated by Django 5.0.4 on 2024-07-10 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_alter_finstatements_fspersonfk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashinacctm',
            name='Section',
        ),
        migrations.RemoveField(
            model_name='cashinacctm',
            name='Statement',
        ),
    ]
