# Generated by Django 4.2.2 on 2023-07-11 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LoginRegister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashinacctm',
            name='AccountNumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ListHeaderT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LHName', models.CharField(max_length=240)),
                ('LHDescription', models.CharField(max_length=240)),
                ('PersonFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListDetailsT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LNNumber', models.IntegerField()),
                ('LHName', models.CharField(max_length=240)),
                ('LHDescription', models.CharField(max_length=480)),
                ('ListDetailFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predecessor', to='LoginRegister.listdetailst')),
                ('ListHeaderFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginRegister.listheadert')),
            ],
        ),
    ]
