# Generated by Django 4.2.2 on 2023-08-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0003_acctrollupsd_transactionst_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sequence', models.CharField(max_length=10, null=True)),
                ('Geography', models.CharField(max_length=120, null=True)),
                ('Population', models.CharField(max_length=40, null=True)),
                ('FTUserCount', models.CharField(max_length=40, null=True)),
                ('Spots1_6Rate', models.CharField(max_length=40, null=True)),
                ('Spot7Rate', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
