# Generated by Django 4.2.1 on 2023-08-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0005_calendarincrements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarincrements',
            name='FamilyID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='calendarincrements',
            name='PersonID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='calendarincrements',
            name='Sequence',
            field=models.IntegerField(null=True),
        ),
    ]
