# Generated by Django 4.2.2 on 2023-08-16 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0004_remove_listdetailst_lhdescription'),
        ('LoginRegister', '0006_alter_calendarincrements_familyid_and_more'),
    ]

    operations = [
    ]
