# Generated by Django 4.2.2 on 2023-08-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0007_merge_20230815_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendars',
            fields=[
                ('calendar', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('calendar_type', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'calendars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('date', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('date_type', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'dates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DefaultParams',
            fields=[
                ('default_param_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'default_params',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('view', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('view_type', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'views',
                'managed': False,
            },
        ),
    ]
