# Generated by Django 4.2.4 on 2023-08-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0009_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransHeaderID', models.IntegerField()),
                ('AccountNumber', models.CharField(max_length=40, null=True)),
                ('Description', models.CharField(max_length=255, null=True)),
                ('DrAmount', models.IntegerField()),
                ('CrAmount', models.IntegerField()),
                ('Created', models.DateField()),
                ('LastUpdated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TransHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransDescription', models.CharField(max_length=120, null=True)),
                ('TransDate', models.DateField()),
                ('TransNote', models.CharField(max_length=240, null=True)),
                ('Created', models.DateField()),
                ('LastUpdated', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='TransactionsT',
        ),
    ]
