# Generated by Django 4.2.4 on 2023-08-24 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0011_transbatch_transheader_transbatchid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transbatch',
            name='Created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transbatch',
            name='LastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transdetail',
            name='Created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transdetail',
            name='LastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transdetail',
            name='TransHeaderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginRegister.transheader'),
        ),
        migrations.AlterField(
            model_name='transheader',
            name='Created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transheader',
            name='LastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
