# Generated by Django 4.2.4 on 2023-09-10 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0014_rename_cramount_transdetail_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashinacctm',
            options={'verbose_name_plural': 'Revenue Accounts'},
        ),
    ]
