# Generated by Django 4.2.4 on 2023-09-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0014_rename_cramount_transdetail_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transdetail',
            name='AccountNumber',
        ),
        migrations.RemoveField(
            model_name='transdetail',
            name='Description',
        ),
    ]
