# Generated by Django 4.2.4 on 2023-09-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0015_remove_transdetail_accountnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transbatch',
            name='TransBatchDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='transheader',
            name='TransDate',
            field=models.DateField(null=True),
        ),
    ]
