# Generated by Django 4.2.4 on 2023-09-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0016_alter_transbatch_transbatchdate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transdetail',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='transbatch',
            name='TransBatchName',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
    ]
