# Generated by Django 4.2.4 on 2023-09-13 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0015_alter_cashinacctm_options'),
        ('LoginRegister', '0017_alter_transdetail_options_and_more'),
    ]

    operations = [
    ]
