# Generated by Django 4.2.5 on 2023-09-16 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0018_merge_20230912_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acctrollupsd',
            options={'verbose_name_plural': 'Account Detail Rollups'},
        ),
        migrations.AlterModelOptions(
            name='acctrollupsm',
            options={'verbose_name_plural': 'Account Rollups'},
        ),
        migrations.AlterModelOptions(
            name='cashoutacctm',
            options={'verbose_name_plural': 'Expense Accounts'},
        ),
        migrations.AlterModelOptions(
            name='debtsacctm',
            options={'verbose_name_plural': 'Liability Accounts'},
        ),
        migrations.AlterModelOptions(
            name='networthacctm',
            options={'verbose_name_plural': 'Equity Accounts'},
        ),
        migrations.AlterModelOptions(
            name='transbatch',
            options={'verbose_name_plural': 'Transaction Batch'},
        ),
        migrations.AlterModelOptions(
            name='transdetail',
            options={'verbose_name_plural': 'Transaction Detail'},
        ),
        migrations.AlterModelOptions(
            name='transheader',
            options={'verbose_name_plural': 'Transaction Header'},
        ),
        migrations.AlterModelOptions(
            name='whatweownacctm',
            options={'verbose_name_plural': 'Asset Accounts'},
        ),
    ]
