# Generated by Django 4.2.6 on 2023-12-01 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0019_alter_acctrollupsd_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listheadert',
            name='PersonFK',
        ),
        migrations.DeleteModel(
            name='ListDetailsT',
        ),
        migrations.DeleteModel(
            name='ListHeaderT',
        ),
    ]
