# Generated by Django 5.0 on 2024-01-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0020_remove_listheadert_personfk_delete_listdetailst_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkClickCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=100, unique=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
